import Head from "next/head";
import Image from "next/image";
import styles from "../styles/PakeServerSideRendering.module.css";

export default function PakeServerSideRendering({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Server Side Rendering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Halaman ini pake{" "}
          <a href="https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props">
            SSR
          </a>
        </h1>

        <p className={styles.description}>
          Coba baca file{" "}
          <code className={styles.code}>
            pages/pake-server-side-rendering.js
          </code>
        </p>

        <div className={styles.grid}>
          {posts.map(({ id, title, body }) => (
            <a href={"/contoh/" + id} className={styles.card}>
              <h2>{title}</h2>
              <p>{body}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts");
  const posts = await response.json();

  return {
    props: {
      posts,
    },
  };
}
